# Generated by Django 3.2 on 2021-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('liter', 'Литров')], max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
    ]
